### ISSUE TITLE
Status of polyfill

### ISSUE THREAD

**Issue by nhynes** [CraneStation/wasi#2]
Is the polyfill currently under active development or would it be worth community contributors' effort? I'd like to test WASI modules in Node, so it'd be great if the polyfill existed!

**Comment by sunfishcode** [comment]
The polyfill code is here: https://github.com/CraneStation/wasmtime/tree/polyfill/wasmtime-wasi/js-polyfill, plus the parts of the WASI implementation that get compiled in.

The link above is on a branch, as on master we've replaced some of the C code in the WASI implementation with Rust code, and the polyfill build doesn't yet support that yet.

The polyfill isn't a major focus right now, but it is an important piece of the big-picture puzzle we're putting together here, so we'd definitely welcome participation. I'd be happy to answer any questions you have.
