### ISSUE TITLE
Polyfill demo page should link to basic information about WASI

### ISSUE THREAD

**Issue by callahad** [CraneStation/wasi#6]
Right now, landing on https://wasi.dev/polyfill/ tells me _nothing_ about what that page is, what's going on, or where to learn more.

It'd be nice if the logo linked somewhere (even just back to https://wasi.dev/ would be fine). It'd also be helpful if there was a single line of text under the logo with more information. E.g., "This is a demo of the browser polyfill for WASI, a [modular system interface for WebAssembly](https://wasi.dev/)"

**Comment by sunfishcode** [comment]
I've now submitted https://github.com/CraneStation/wasi.dev/pull/6 to fix this.

**Comment by sunfishcode** [comment]
And it's now merged. Thanks for the report!
